microsoft/java-debug

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

This feature will also resolve these bugs: 
https://github.com/Microsoft/java-debug/issues/24
https://github.com/Microsoft/vscode-java-debug/issues/46
https://github.com/Microsoft/vscode-java-debug/issues/21

Support uri in Source.path

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java

Improve the call stack display info for not avialable source

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/UsageDataSession.java

[Error - 3:28:50 PM] Oct 12, 2017 3:27:33 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
at com.microsoft.java.debug.core.UsageDataSession.getSessionGuid(UsageDataSession.java:45)
at com.microsoft.java.debug.core.UsageDataStore.logErrorData(UsageDataStore.java:84)
at com.microsoft.java.debug.plugin.internal.UsageDataLogHandler.publish(UsageDataLogHandler.java:34)
at java.util.logging.Logger.log(Logger.java:738)
at java.util.logging.Logger.doLog(Logger.java:765)
at java.util.logging.Logger.log(Logger.java:876)
at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.resolveClasspaths(ResolveClasspathsHandler.java:52)
at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(Jav …

fix java.lang.NullPointerException bug

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugEvent.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/EventHub.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java

fix bug https://github.com/Microsoft/vscode-java-debug/issues/14

Avoid two stopped events for step and breakpoint

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java

Handle the vscode bug: https://github.com/Microsoft/vscode/issues/36471

fix the inconsistent uri issue for set breakpoint request

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java

fix bug #49.
Nested types are just needed for those already loaded classes. For the referenceType from ClassPrepareEvent, no need to search the locations in the nested types. For newly loaded classes, the debugger has also registered ClassPrepareRequest for their local types, so the debugger will handle the local types in ClassPrepareEvent handler.

Fix perf issue on get locations of breakpoint

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IDebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/AbstractJdiTestCase.java
com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/DebugSessionFactory.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtVirtualMachineManagerProvider.java

@testforstephen @andxu @akaroml

Refator IDebugSession & IProvider

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java

fix bug https://github.com/Microsoft/vscode-java-debug/issues/183

Fix bug 183: No need to create exception request when no exception breakpoints are requested

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java

@akaroml @andxu @testforstephen

Redefine HCR event.

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/StackFrameUtility.java

@akaroml @testforstephen @andxu 
For spring case, it will try to pop stack above native methods but it will failed. It is the design behavior of JVM and similar behavior in eclipse. 
However, the exception is https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/InternalException.html instead of more specific https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/NativeMethodException.html, just try the general runtime exception as eclipse did. 
We need document the non support scenarios here.

Fix general exception for native methods.

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java

https://github.com/Microsoft/vscode-java-debug/issues/182

fix jdt bug of ObjectCollectedException on ExceptionRequest.enable.

---

com.microsoft.java.debug.core/pom.xml
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
pom.xml

Fix the issue https://github.com/Microsoft/java-debug/issues/145.

Fix the project's build errors in JDK 9/10

---

com.microsoft.java.debug.repository/pushToBintray.sh

I didn't find any existing jenkins plugin to deploy to bintray, so add a script to push the p2 artifacts to bintray.
The index page https://dl.bintray.com/vscjavaci/javadebug/ will show the latest version:
The sub path https://dl.bintray.com/vscjavaci/javadebug/releases will list the history:

Add script to push p2 artifact

---

.project
.travis.yml
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugException.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/CompletionsHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/RestartFrameHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetExceptionBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetVariableRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java

The request is from https://github.com/Microsoft/vscode-java-debug/issues/333
This PR will log the detailed error message for error response.

Add log coverage for error response

---

com.microsoft.java.debug.repository/pushToBintray.sh

The `mvn help:evaluate` command doesn't work at the Jenkins shell environment, choose to pass it via the external command line argument.

Pass the pom version via the cli args

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java

Previously the constructed `envVars` are mistakenly not returned. 
See https://github.com/Microsoft/vscode-java-debug/issues/393

Fix: correctly return contructed envrionment variables.

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java

Avoid to call search engine to get project when only one project in workspace

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/AdvancedLaunchingConnector.java

https://github.com/Microsoft/vscode-java-debug/issues/440

fix #440: The startup command arguments for internalConsole are different from integratedTerminal

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java

The search engine will return other classes whose class name contains the searching text, this will cause the main class isn't unique issue.

Fix the main class isn't unique issue

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java

Fixes Microsoft/vscode-java-debug#541

Increase the timeout when attaching to integrated/external terminal

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructure.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructureManager.java

fixes Microsoft/vscode-java-debug#571
fixes Microsoft/vscode-java-debug#568
Use the evaluation engine to resolve the logical structure, it has perf issue. On the other hand, in JDK 11, jdt has an issue on parsing the compiled expression `return entrySet();` for Map. See jdt issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=543604.
The PR will get the logical structure via the JDI approach. It will fix perf issue and JDK 11 problem.

Fix variable perf issue & logical structure doesn't work with JDK 11

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java

Fixes Microsoft/vscode-java-debug#582

Fix bug: the debug toolbar doesn't close after the program running in terminal has exited

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java

Now it will cost about 5 seconds in the destroyLaunchFiles function,
there should have a break statement if no IOException is caught
in each loop iteration for better performance.
Signed-off-by: tom-shan <s00347147@163.com>

Break out of the while loop for better performance

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java

Accept an optional `launcherScript` in launchArgs, and prepend it to launch cmds.

Support to use a launcher to run in terminal

---

README.md

Just an idea. Probably there's a better way to do this. But for those getting started with Java again (and not as familiar with maven wrapper script), it did take a minute to figure out what to do to get it installed (i.e., that `mvn clean install` doesn't work).

Add minor installation note in README.md about mvnw.cmd/mvnw

---

.vscode/launch.json
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/DisconnectRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java

Clean up the resources generated by HCR provider

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java

Use -m prefix only when the main class is contained in a module

---

pom.xml

In JDK 13, build command will fail. Up tycho version to 1.5.1 to support the latest JDK.

Up tycho version to 1.5.1

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableUtils.java

Allows for fix for [microsoft/vscode-java-debug#745](https://github.com/microsoft/vscode-java-debug/issues/745#issue-547078106)

Added debugger user setting for setting numeric precision

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
com.microsoft.java.debug.plugin/plugin.xml
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveJavaExecutableHandler.java

This PR requires https://github.com/microsoft/vscode-java-debug/pull/758

Use project's java runtime to launch the application

---

check_style.xml
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/LogUtils.java
pom.xml

update checkstyle to 8.29

---

README.md

May be helpful for people who try to use java-debug with other clients
than Visual Studio Code.

Extend readme with basic low level usage instructions

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ScopesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetVariableRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructure.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructureManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/Variable.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableProxy.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java

Signed-off-by: Jinbo Wang jinbwan@microsoft.com
Close microsoft/vscode-java-debug#819
Close #290

Support copying variable

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java

Fix microsoft/vscode-java-debug#855
Root cause:
Previously the extension uses Set to dedup the changed resources and classes. One exceptional case is for multiple module maven projects, the classes changed in sub module also appear in the resource change listener of the parent project. Use HastSet cannot dedup the resource object even though they are pointing to the same physical file.

Dedup the changed classes before hot reload

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveJavaExecutableHandler.java

Fix microsoft/vscode-java-debug#882

Fix Java exec exception 'UNC path is missing sharename'

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveJavaExecutableHandler.java

When attaching to an existing debuggee program, its runtime version may be different with the one that the debugger used to build your project. Although the debugger still works when the JDK mismatches. But stepping into the JDK system library, the native library source line may be not consistent with the remote one and cause the line mismatch during stepping. For such case, the debugger will print a warning message when runtime is not matched in the DEBUG CONSOLE view.

Use the correct runtime to validate the JVM versions between the debugger and debuggee

---

.project
com.microsoft.java.debug.core/.project
com.microsoft.java.debug.plugin/.project
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java
com.microsoft.java.debug.repository/.project

Fix microsoft/vscode-java-debug#880

Fix the wrong completion list in debug console

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java

Fixes microsoft/vscode-java-debug#822

Add quotes to the argfile argument if the argfile path contains space

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java

Fixes microsoft/vscode-java-debug#909

Sort completion by relevance & respect completion filters registered by JLS

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java

Fixes microsoft/vscode-java-debug#924

Avoid using the same temporary launch file when triggering multiple debug sessions in parallel

---

com.microsoft.java.debug.core/pom.xml
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java
com.microsoft.java.debug.plugin/.classpath
com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
com.microsoft.java.debug.plugin/pom.xml
com.microsoft.java.debug.repository/category.xml
com.microsoft.java.debug.repository/pom.xml
pom.xml

sun.* is the JDK internal API, and not supposed to be used by the external application.
Fixes microsoft/vscode-java-debug#970

Remove the usage of JDK internal API to avoid breaking JDK 16

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java

requires https://github.com/microsoft/vscode-java-debug/pull/1005

Support customizing the classpaths and modulepaths

---

com.microsoft.java.debug.plugin/.classpath
com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF

This is a follow-up to PR #380. Previous PR updated commons-io to 2.10.0 to fix vulnerability, but missed updating the library version in eclipse project file.

Fix the commons-io version issue in project file

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java

'SourceVersion.isName' is a utility method from JDK class, it can be used to validate if a class name is a valid qualified name.
Fixes microsoft/vscode-java-debug#780

Allow mainClass to be configured with unicode characters

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java

Fixes microsoft/vscode-java-debug#1047

Fix: classpath is not generated into argfile when using shortCommanLine=argfile

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java

Fixes microsoft/vscode-java-debug#1044
Since JDI does not provide an efficient way to query whether a variable is a large object or not. One way to mitigate this is to intercept OOM or timeout exceptions that occur when fetching variable information and display a placeholder on these failed variable segments. This way, the user still has the opportunity to view the basic variable information.
**Before** - Variables view just displays an Exception message.
**After** - Variables view still lists all variables, but displays a placeholder for the failed variable property.

if listing the variable value of a large object fails, just display its basic info

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProcessConsole.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

This requires https://github.com/microsoft/vscode-java-debug/pull/1077
This project is an implementation of DAP, it's better to keep encoding neutral. It's the client's responsibility to determine what encoding to use to launch user's application.

Make DAP implementation to be encoding-neutral

---

com.microsoft.java.debug.core/.classpath
com.microsoft.java.debug.core/pom.xml
com.microsoft.java.debug.plugin/.classpath
com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
com.microsoft.java.debug.plugin/pom.xml
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainMethodHandler.java
java.debug.target
pom.xml

Previously opening java-debug project in VS Code, it reports lots of errors about JDI classes. See the issue https://github.com/redhat-developer/vscode-java/issues/1551
Now that the Java Language Support Extension has embedded JRE 17 to run all Java extensions, it's time to migrate the Java Debug extension to Java 11. 
Meanwhile, with this PR, it supports running unit tests for Java Debug through VS Code Test Explorer.
Close #388

Migrate to Java 11

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java

- Allow searching main class from the specified project name
- Limit search scope of search engine to SOURCES, this can boost main class resolving performance a lot

Limit search scope of main class to source files and the specified project or paths

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/LaunchException.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/AdvancedLaunchingConnector.java

Resolves #397 or at least contributes to it

Report more detail in VM start errors

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Events.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java

This change sends logpoint messages as protocol events to the vscode-java-debug extension, instead of printing them to `System.out` of the process being debugged.
Fixes microsoft/vscode-java-debug#710

Send logpoint messages to the debug console

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableDetailUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableProxy.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java

requires: https://github.com/microsoft/vscode-java-debug/pull/1134
specification: https://microsoft.github.io/debug-adapter-protocol/specification#Types_VariablePresentationHint
demo:
more details can be found in https://github.com/microsoft/vscode/issues/135147, and there is still a UX discussion.

Support lazy loading object values from toString()

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithoutDebuggingDelegate.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ProcessIdHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Events.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Responses.java

request: 'processId'
response:
{
processId?: long;   // The process id
shellProcessId?: long;   // The process id of the terminal if the Java process is running in a terminal
}

customRequest 'processId' to get the debugging Java process id

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/DisconnectRequestWithoutDebuggingHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithoutDebuggingDelegate.java

It does two things in this PR:
- Capture the Java process pid when running Java in a terminal shell.
This is a follow-up of https://github.com/microsoft/java-debug/pull/399. Both the SpringBoot Dashboard and Spring Tools extension have the requirement to get the running Java pid from Java debugger, so it makes sense to support it in Java debugger directly for reuse.
Since the DAP just returns the shell process pid when running Java in a terminal shell, the debugger have to find the running Java process based on the shell pid. In the standard shell environment such as PowerShell, cmd, Linux/macOS shells, the shell process is parent of Java process, it's easy to find Java subprocess from process tree. But this approach fails when using Git Bash as the default terminal, because the launched …

Capture Java process pid and display debug toolbar when running Java in terminal

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithDebuggingDelegate.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithoutDebuggingDelegate.java

Fixes microsoft/vscode-java-debug#1164
Naming the terminal for "Run Java" action as "Run \<MainClassName\>". For "Debug Java" action, naming it as "Debug \<MainClassName\>". The same debug session will reuse the same terminal. And it can also differentiate the Run and Debug behavior.

Naming Java terminal with mainClass name

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java

This causes some clients to display the frames in a different way, e.g
by graying them out.

Mark native frames and unavailable methods as subtle

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BreakpointLocationLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

Now method breakpoints can added by adding a line breakpoint at method
header.

Improve support for method breakpoints

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java

This changes the result of an expression like `Long.parseLong("foo")`
sent to the evaluate handler from:
org.eclipse.debug.core.DebugException: com.sun.jdi.InvocationException: Exception occurred in target VM occurred invoking method.
to the actual exception:
NumberFormatException@76 "java.lang.NumberFormatException: For input string: "foo""
backtrace: Object[6]@82
cause: NumberFormatException@76
depth: 46
detailMessage: "For input string: "foo""
stackTrace: StackTraceElement[0]@84
suppressedExceptions: Collections$EmptyList@85 size=0
I think this makes the console in vscode and other DAP clients more useful as you get a more meaningful result for expressions that fail

Show target VM exceptions as result in evaluate requests

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/EvaluatableBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/BreakpointManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BreakpointLocationLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/LambdaExpressionLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

The support for method header breakpoints was extended to support
lambda breakpoints using the vscode inline breakpoint feature.

Add support for lambda breakpoints

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/AsyncJdwpUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IMethodBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/MethodBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/UsageDataSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IStackFrameManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/StackFrameManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ThreadCache.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InlineValuesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/RestartFrameHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetFunctionBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/StringReferenceProxy.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableUtils.java

This PR provides some experimental performance tuning for remote debugging:
- Add a thread cache to reduce JDWP frequency for thread info. `threads` request is the most frequent DAP request, and adding a cache can save lots of unnecessary JDWP queries.
- Provide async mode to process JDWP commands in parallel. This hopes to improve the DAP responsiveness on high-latency networks.

Perf: support sending JDWP commands asynchronously

---

com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/NumericFormatterTest.java

In certain regions (e.g. Brazil, Germany, etc.), a comma is used instead of a dot as a decimal separator by default.
This change will set the default locale to US (so a dot is used as a decimal separator) before performing numeric formatter tests.
This PR fixes #337. Solution already addressed by @siqueira-gustavo (full credit goes to him), but no changes have been made.

Fixes NumericFormatter failure on systems with other decimal separator

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ThreadCache.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ExceptionInfoRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetDataBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetFunctionBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java

Address https://github.com/microsoft/vscode-java-debug/issues/1159.
What this PR does:
- For thread start and thread death events, restrict the events so they are only sent for platform threads. Since the number of virtual threads can be large, this prevents DAP from being busy with thread events.
- In the Threads view, we only list those virtual threads that are suspended by events (e.g. BreakpointEvent, StepEvent, etc.).

Support for debugging virtual threads

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/EvaluatableBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IBreakpoint.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IDebugSession.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/JavaBreakpointLocation.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/BreakpointLocationsRequestHander.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Responses.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/LambdaExpressionLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

What this PR does:
- Support BreakpointLocations DAP Request, this can visualize the locations where inline breakpoints can be added. Closes microsoft/vscode-java-debug#1193.
- Show an extra column cursor when an inline breakpoint is hit. Closes microsoft/vscode-java-debug#1202
- Line breakpoint will only break on the first location on that line. If the line contains other lambdas, you can add an inline breakpoint to break on other locations.

Visualize the inline breakpoint locations

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepInTargetsRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/StackFrameReference.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Responses.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BindingUtils.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BreakpointLocationLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/LambdaExpressionLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/MethodInvocationLocator.java

The change implement the StepInTarget request and also update the
StepRequestHandler to support StepInTarget as well.

Add support for StepInTarget request

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IStackFrameManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/StackFrameManager.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java

Fixes microsoft/vscode-java-debug#1250
In old behavior, conditional breakpoint will store some stale stackframes in the cache so that its length doesn't match the new conditional breakpoint's stackframe length.
Fix: conditional breakpoint doesn't need to reload the stack frames if the thread's stackframes are not used before.

Conditional Breakpoint got error code in reply:504

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java

Fixes microsoft/vscode-java-debug#1254

"shortenCommandLine": "argfile|auto" should include "vmArgs"

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/Compile.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java

- For a build-tool managed project, will check if the running project and its references projects contain build errors. If so, report build failure. Otherwise, return succeed.
- For unmanaged folder, only check if the running main class contains build errors. If so, report build failure. Otherwise, return succeed.

Only report build failure when the build errors are on the running project's classpath

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/InlineValueHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java

If there is an identical class file A .java in the project and the dependency, then the A .java under the project should be found first during debugging.
Fixes microsoft/vscode-java-debug#1215

prioritize lookup the project source code during debugging

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BindingUtils.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/BreakpointLocationLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/LambdaExpressionLocator.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java

The issue seems to be when resolving lambda method for reactive operators, the binding resolver is not the default binding resolvers which actually resolves the lambda method. 
It seems. the AST construction effects which binding resolver is used at runtime in the node. Therefore switched to the using cache AST when available which seems to resolved the issue. Will do some more testing.

Improve lambda method discovery Fixes: #477

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterFactory.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java

I'm building a Java DAP server based on `com.microsoft.java.debug.core` for our internal projects based on Buck. The goals is to enable debugging without relying on Eclipse LSP. So I'm customizing the part that is resolving source locations based on our internal language tooling and the dependency graph knowledge available in Buck. 
`com.microsoft.java.debug.core` works really well for me as I'm able to completely reuse JDWP <-> DAP interaction while replacing providers with my own implementation. This works quite well.
Additionally our binaries are quite customised so I'd like to also provide custom implementations for "initialize", "launch" and "setFunctionalBreakpoints" requests without necessarily rewriting `ProtocolServer` and `DebugAdapter`
This PR is enabling me to inherit …

Add extensibility points to DebugAdapter and ProtocolServer

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/BreakpointTest.java

The fix tries to compare the runtime lambda method signature with none generic version of the method signature found from AST traversal as a additional comparison to what is there.

Fix generic return type lambda breakpoint issue. Fix #1359

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/Source.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/SourceType.java
com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java

I'm building a DAP server based on `core` package. I.e. without eclipse plugin. Currently it's impossible to set "sourceReference" when returning types in "stacktrace" request. 
Having a distinction between Local and Remote sources allows an implementation of ISourceLookUpProvider to instruct the underlying request handlers whether a follow up with "source" request and have it served via `getSourceContents`
This is also ABI compatible with whoever could implement ISourceLookUpProvider already as current logic is identical to SourceType.Local
I've tested this works with my DAP server

Extend ISourceLookUpProvider to be able to specify whether the source is Local (VSCode) or Remote(DAP Server) 

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/MethodInvocationLocator.java

The fix try to compare the current line number against the target MethodInvocation start line if the debugger lines doesn't match because the current frame is at a wrapped line even though we are executing the same expression.

Fix the step-into target on multi line expression. Fix #519

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
pom.xml

Fix build errors

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/Compile.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java

- when HCR request comes, find the main project and check if it's a 
gradle build server project, if yes, trigger the incremental build.
requires: https://github.com/microsoft/vscode-gradle/pull/1493
replace the following jar file into the vscode gradle extension installation path, under the `server` folder
[com.microsoft.gradle.bs.importer-0.2.0.jar.zip](https://github.com/user-attachments/files/15530193/com.microsoft.gradle.bs.importer-0.2.0.jar.zip)
Launch debugger extension with this change.
fix https://github.com/microsoft/vscode-gradle/issues/1449
fix https://github.com/redhat-developer/vscode-java/issues/3392
fix https://github.com/microsoft/vscode-java-debug/issues/1402
fix https://github.com/microsoft/vscode-java-debug/issues/1481
fix …

Support HCR for gradle build server projects

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/AdvancedLaunchingConnector.java

Launching a Java app in the CONSOLE with java 23, it still reports some warning `OpenJDK 64-Bit Server VM warning: The java.compiler system property is obsolete and no longer supported, use -Xint`.

Remove the obselete parameter '-Djava.compiler=NONE' from launching command

---

com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target

New version of jdtls core requires lsp4j 0.23 or greater.
With 0.22.0 the build currently fails with the following error:
```
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.jdt.ls.core 1.39.0.202408021530
[ERROR]   Missing requirement: org.eclipse.jdt.ls.core 1.39.0.202408021530 requires 'osgi.bundle; org.eclipse.lsp4j [0.23.0.0,0.24.0)' but it could not be found
[ERROR]
```

Update lsp4j dependency to version 0.23.1

---

com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target

Using current version of [4.33-I-builds](https://github.com/microsoft/java-debug/blob/3691f3b5f2cae05b06b43333dc435c172e27f1a8/com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target#L18) yields this error when trying to `./mvnw clean install`:
```
Failed to load p2 metadata repository from location https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240613-1800:
No repository found at https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240613-1800.
```
Tried to use just [4.33](https://download.eclipse.org/eclipse/updates/4.33/) instead and the error is gone now.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Java Debug Server for Visual Studio Code :: Parent 0.53.0:
[INFO]
[INFO] Java Debug …
```

Update eclipse to use v4.33

---

com.microsoft.java.debug.plugin/.classpath
com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
com.microsoft.java.debug.plugin/pom.xml
com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target

- Update Apache Commons IO from 2.11.0 to 2.19.0
java-debug is a bundle contributed into the JDT-LS runtime. This means that it has no control over any dependencies it dos not contribute into the runtime itself (all of them). So when java-debug defines a target platform with dependencies that don't reference the same ones JDT-LS does, it is masking any potential runtime problems. This is the same issue we ran into on LSP4MP / quarkus-ls. The project will compile just fine and fail at runtime because the target platform is not reflective of runtime.
The solution is to reference the exact bundles JDT-LS is using (ie. the latest ones), at https://download.eclipse.org/jdtls/snapshots/repository/latest/plugins/ .

Update target platform to more closely follow JDT-LS.

---

com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java
com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target

switch sha256 to calculate temp file name

---

com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java

Improve ResolveMainClassHandler.resolveMainClassUnderPaths
