microsoft/java-debug

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
add for feature https://github.com/Microsoft/java-debug/issues/43
> format stackframe name with ClassName.MethodName(ParameterTypes)

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
Signed-off-by: xuzho <xuzho@microsoft.com>
#21
> fix bug: jdt search might return multiple same projects

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> bump version to 0.2.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java
fix bug https://github.com/Microsoft/vscode-java-debug/issues/122
> Fix regression bug #122

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
Signed-off-by: xuzho <xuzho@microsoft.com>
> support stop on entry

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> Bump version to 0.3.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
Signed-off-by: xuzho <xuzho@microsoft.com>
> fix bug: stopOnEntry doesn't support java9

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/UsageDataSession.java
> add synchronize statement for modifying eventlist and serializing it

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> upgrade with new version 0.3.1 for hotfix

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebuggerServerPlugin.java
Fixes #101 
Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>
> Invalid plugin ID

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapter.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/DisconnectRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ScopesRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetExceptionBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetVariableRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SourceRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/AbstractProtocolServer.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugServer.java
> [Refactor] use CompletableFuture to support async response in debug adapter

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java
@ansyral @akaroml @andxu @testforstephen
> Add project scope when resolving multiple-root project.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
fix bug: 100% CPU when debugging sprint boot pet clinic with "stopOnEntry" on (https://github.com/Microsoft/vscode-java-debug/issues/145).
The root cause: previous implementation doesn't clean up the methodEntryRequest when the stopOnEntry is hit. The later program always do string compare to filter if it's the main method. This is the reason why stopOnEntry slow down the debuggee program.
> Fix perf issue when debugging pet clinic with "stopOnEntry" on

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/AbstractProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/IProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/JsonUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Messages.java
> Support send request in protocol server

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> bump version to 0.4.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugException.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ErrorCode.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Responses.java
> Provide launchInTerminal feature to support console input

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> Add required info in pom.xml to pass nexus validation

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IHotCodeReplaceProvider.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
@andxu @testforstephen @akaroml @ansyral
> Add HCR mechanisms.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
This is to enforce sequential processing for features like Expression Evaluation and HCR.
> Sequentially process debug requests

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
@andxu @akaroml @testforstephen
> Add enable hot code replace settings.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/AbstractProtocolServer.java
Fix Microsoft/vscode-java-debug#208
> Use proper scheduler to unblock request/response streams

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/StackFrameUtility.java
@akaroml @testforstephen @andxu
> Fix issue when poping the top stack frame from a thread.

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
@akaroml @testforstephen @andxu
> Fix the error case when contain the obsolete methods.

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
@akaroml @andux @testforstephen
> Bump version to 0.6.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
@testforstephen @andxu @akaroml
> Fix VMDisconnectionException.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
1. Basic flow to handle breakpoint and condition.
> PR1 of conditional BP

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/Constants.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Events.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java
since andy_dev4 is merged to master, close this one and create a new one instead
> notify user when error is raised when evaluating breakpoint condition[1]

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/UsageDataStore.java
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
@andxu @testforstephen @akaroml
> Clean up engineering setting debts.

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
@andxu @testforstephen  @akaroml
> Bump version to 0.8.0.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/RestartFrameHandler.java
@andxu @testforstephen @akaroml
> Rephrase the stop event for the restart frame.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapter.java
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtProviderContextFactory.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtUtils.java
@andxu @testforstephen @akaroml
> Add auto completion implementation for debug console.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
https://github.com/Microsoft/vscode-java-debug/issues/277
> fix issue 277: Don't stop on caught/uncaught exceptions

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AttachRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
> Setup initialize for completion provider.

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> Bump version to 0.9.0

- pom.xml
> Fix build breaks.

- java.debug.target
- javaProject.json
> Support PDE development.

- .gitignore
- .project
- com.microsoft.java.debug.core/.classpath
- com.microsoft.java.debug.core/.project
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/.project
- java.debug.target
> Add eclipse settings.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/EvaluatableBreakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IBreakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IDebugSession.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IEvaluatableBreakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/BreakpointManager.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IEvaluationProvider.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/InitializeRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Types.java
- com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/AbstractJdiTestCase.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java
> Support logpoint feature for java debugger

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- pom.xml
> Bump version 0.10.0

- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
The request is from https://github.com/Microsoft/java-debug/issues/188
The PR will build a p2 artifacts for com.microsoft.java.debug.plugin, and it will showed as the following format:
> Add p2 update site

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.11.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java
Fix NPE issue https://github.com/Microsoft/java-debug/issues/200
> Fix NPE for CompletionsProvider

- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
Redhat.java update to version 0.30.0 broke launching/debugging of Spring boot-apps 
#402
> Fix issue #402 missing runtime scope classpath entry

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainMethodHandler.java
This is for the issue https://github.com/Microsoft/vscode-java-debug/issues/375
> Add a utility to resolve main methods from a java file

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugUtility.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
> Use user-specified java home to launch debuggee

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ProtocolServer.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/RestartFrameHandler.java
It fixes the bug https://github.com/Microsoft/vscode-java-debug/issues/411 and https://github.com/Microsoft/java-debug/issues/134
> Fix debug buttons disabled issue: send StoppedEvent after StepResponse/ContinueResponse

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
https://github.com/Microsoft/vscode-java-debug/issues/369
> fix the InvalidStackFrameException

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainMethodHandler.java
It fixes the issue https://github.com/Microsoft/vscode-java-debug/issues/438
> Fix codeLens for Run/Debug links showing up with latency

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java
It fixes the bug https://github.com/Microsoft/vscode-java-debug/issues/437
> Fix the validation issue for main class name

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version 0.14.0

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version to 0.15.0

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.16.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/LaunchCommandHandler.java
Reference the PR https://github.com/Microsoft/vscode-java-debug/pull/532 for the usage.
> Add utility command to get the launch command length

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.17.0

- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionsProvider.java
Signed-off-by: Yaohai Zheng <yaozheng@microsoft.com>
> Add completion support for classfile.

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
> Don't show static fields by default

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> up version to 0.18.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
> Log the logical structure evaluation error

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ProjectSettingsChecker.java
This is the utility for the PR https://github.com/Microsoft/vscode-java-debug/pull/561
> Add utility to check java project settings

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
fixes Microsoft/vscode-java-debug#575
> Fix the perf for evaluation result

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IEvaluationProvider.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructure.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/JavaLogicalStructureManager.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java
fixes Microsoft/vscode-java-debug#574
fixes Microsoft/vscode-java-debug#575
> Fix the stack frame conflicts between logical structure and evaluation

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ConfigurationDoneRequestHandler.java
> Fix bug: cannot stop the debug session automatically in attach mode

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
> Support debug settings to control how to trigger HCR

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/HotCodeReplaceHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Responses.java
> Return the changed classes as response of redefine classes command

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/formatter/ObjectFormatter.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/formatter/StringObjectFormatter.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/EvaluateRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableDetailUtils.java
- com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/ArrayObjectFormatterTest.java
- com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/ClassObjectFormatterTest.java
- com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/ObjectFormatterTest.java
- com.microsoft.java.debug.core/src/test/java/com/microsoft/java/debug/core/adapter/formatter/StringObjectFormatterTest.java
Close microsoft/vscode-java-debug#315
Close microsoft/vscode-java-debug#364
For the classes that override 'toString' method, show `toString()` details.
For Collection and Map classes, show an additional `size=x` details.
For Entry, show `key:value` details.
> Variable: Show toString() value for the classes that override toString method

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.19.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
Fix microsoft/vscode-java-debug#584
Fix microsoft/vscode-java-debug#566
Currently, we're using `JavaRuntime.resolveRuntimeClasspath(IJavaProject)` API, there are two limitation for it.
- It used DFS algorithm to deal with dependency. It violates the [maven dependency mechanism](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html), which uses BFS to deal with dependency chain.
- It cannot handle `test` scope.
The fix is to use the corresponding class provider for different project type to resolve the runtime classpath.
- maven project - MavenRuntimeClasspathProvider
- gradle project - GradleRuntimeClasspathProvider
- eclipse project - StandardClasspathProvider (default)
> For different project types, use the corresponding class provider to resolve the runtime classpath

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
For maven project, it will be delegated to m2e plugin to compute the classpath. M2E will check whether there is any mapped resource belonging to test folders, if so, then use test scope to compute classpath, otherwise use runtime scope to compute classpath. So if the main class is in test folders, it requires us to explicitly pass the mapped test resources to the launch configuration.
> Pass the mapped test resources to launch configuration to help m2e to detect test scope

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.20.0

- .travis.yml
- check_style.xml
- pom.xml
Do not force checkstyle check locally, as some devs (Windows) checkout code as CRLF.
> Check style only on Travis CI

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version to 0.21.0

- java.debug.target
- pom.xml
> Update pde target definition

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveElementHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainMethodHandler.java
> Add command to check if the hovered element is main method

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version to 0.22.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
> Reuse the temp file name for the same project when shorten the classpath

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
> Add command to resolve the project build files

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
> Check whether java file is on classpath

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainClassHandler.java
> Support searching main classes from the workspace invisible project

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version to 0.23.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
Fix microsoft/vscode-java-debug#711
> Auto append brackets when auto complete function in DEBUG CONSOLE view

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.24.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchWithoutDebuggingDelegate.java
Fix microsoft/vscode-java-debug#719
> Fix NPE when searching the source for the exception stack trace

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebuggerServerPlugin.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/LogUtils.java
> Clean up the registered logger handlers when stopping the plugin

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/protocol/Requests.java
> Provide custom request to support continue/pause all/other threads

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> up version to 0.25.0

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java
fix microsoft/vscode-java-debug#752
> Return disconnect response in 500ms

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- java.debug.target
- pom.xml
Fix microsoft/vscode-java-debug#773
> Update ASTParser to support Java 13 syntax

- com.microsoft.java.debug.plugin/plugin.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebugDelegateCommandHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/PlatformSettings.java
> add a helper command to get the jdt platform settings

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/EvaluatableBreakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/IEvaluatableBreakpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Watchpoint.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/AbstractDisconnectRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/eval/JdtEvaluationProvider.java
Fix microsoft/vscode-java-debug#782
> Fix race competition when the breakpoint needs be evaluated in multi threads

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> bump version to 0.26.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveClasspathsHandler.java
Fix microsoft/vscode-java-debug#715
> Fix gradle test scope

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/JdiMethodResult.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/DebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IDebugAdapterContext.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/IStepResultManager.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/StepResultManager.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StepRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ThreadsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/VariablesRequestHandler.java
Close microsoft/vscode-java-debug#660
> Display the method return value when stepping out

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
Fix microsoft/vscode-java-debug#824
> Fix the call stack matching regex expression for modules

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/ExceptionInfoRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/variables/VariableUtils.java
Fix microsoft/vscode-java-debug#767
> Fix the InvalidStackFrameException when getting variables at the exception breakpoint

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
> Bump version to 0.27.0

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaHotCodeReplaceProvider.java
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
Fix microsoft/vscode-java-debug#850
> Fix HCR not working issue

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
fixes microsoft/vscode-java-debug#973
> Fix bug#973: breakpoints inside record don't work

- com.microsoft.java.debug.core/pom.xml
- com.microsoft.java.debug.plugin/.classpath
- com.microsoft.java.debug.plugin/META-INF/MANIFEST.MF
- com.microsoft.java.debug.plugin/pom.xml
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/AdvancedLaunchingConnector.java
- com.microsoft.java.debug.repository/category.xml
- com.microsoft.java.debug.repository/pom.xml
- pom.xml
Fixes microsoft/vscode-java-debug#995
> Fix the broken due to the changes from the upstream JDI impl class ConnectorImpl$StringArgumentImpl

- ThirdPartyNotices.txt
See microsoft/vscode-java-pack#768 to add ThirdPartyNotices.txt
> Add ThirdPartyNotices.txt

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java
Fixes microsoft/vscode-java-debug#1173
> Increase polling frequency to ensure that Java processes are detected

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JavaDebuggerServerPlugin.java
> Fix NPE from logHandler when stopping debug plugin

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/LaunchUtils.java
Fixes microsoft/vscode-java-debug#1112
According to the java spec, the argument file must contain only ASCII characters or characters in system default encoding that's ASCII friendly.
https://docs.oracle.com/en/java/javase/18/docs/specs/man/java.html#java-command-line-argument-files
> Use the system encoding to generate the *.argfile

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSettings.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/JavaBreakpointLocation.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/AdapterUtils.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/ISourceLookUpProvider.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/SetBreakpointsRequestHandler.java
- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/adapter/handler/StackTraceRequestHandler.java
- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/JdtSourceLookUpProvider.java
- com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
this depends on redhat.java@1.20.2023062004 and later to make it work.
> Debug support on the decompiled source code

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/Compile.java
requires: https://github.com/microsoft/vscode-gradle/pull/1368
> Only build main project for build server project

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
Fixes microsoft/vscode-java-debug#1246
Before:
- Always use the simple name and eval will fail due to unresolved type.
https://github.com/microsoft/java-debug/assets/14052197/03f13bc5-1584-4bd9-91a8-8d13804626ef
New:
- For the imported types or types from sample package, use the simple name
- For the unimported types, use the fully qualified name
https://github.com/microsoft/java-debug/assets/14052197/09c22a7c-2e46-4746-818f-6e1d490c539c
> Code completion: Use fully qualified name as needed in DEBUG CONSOLE

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/CompletionProposalRequestor.java
> Code completion: Display the package name in the label property when suggesting types in DEBUG CONSOLE

- com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
> Update target platform dependencies to fix build errors

- com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
> updated dependency location

- com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
> Update com.microsoft.java.debug.tp.target to 4.31 release

- com.microsoft.java.debug.target/com.microsoft.java.debug.tp.target
> Update lsp4j to 0.22.0

- com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/AdvancedLaunchingConnector.java
> Remove the deprecated debug parameters from the launching connector

- com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/DebugSession.java
Fixes https://github.com/microsoft/vscode-java-debug/issues/1274
> Shutdown process normally if possible
